### ISSUE TITLE
sc failing to read csv converted from xlsx

### ISSUE THREAD

**Issue by Jemi** [n-t-roff/sc#17] opened 2020-02-16 20:03 UTC
sc fails to open csv file converted from unoconv. Github won't let me attach csv files so I'm attaching here the xlsx from which it was converted. The command I used to convert the file was unoconv -f csv -o NGSL+1.01+with+SFI.csv NGSL+1.01+with+SFI.xlsx . 

with sc -q NGSL+1.01+with+SFI.csv these are the kinds of errors i get:

Unintelligible word: flee<=,,,52.804,19.07,0.8819,"5,898","3,060",0.0000,0.92

syntax error: flee<=,,,52.804,19.07,0.8819,"5,898","3,060",0.0000,0.92

Unintelligible word: bay<=,,,52.799,19.05,0.8763,"5,927","3,050",0.0000,0.92

syntax error: bay<=,,,52.799,19.05,0.8763,"5,927","3,050",0.0000,0.92

Unintelligible word: constitutional<=,,,52.794,19.03,0.8547,"6,053","3,011",0.0000,0.92

syntax error: constitutional<=,,,52.794,19.03,0.8547,"6,053","3,011",0.0000,0.92

**Comment by Jemi** [comment] 2020-02-16 20:04
Attaching NGSL+1.01+with+SFI.xlsx:

[NGSL+1.01+with+SFI.xlsx](https://github.com/n-t-roff/sc/files/4210839/NGSL%2B1.01%2Bwith%2BSFI.xlsx)

**Comment by n-t-roff** [comment] 2020-02-20 19:56
Thank you for reporting the issue. Unfortunately I don't have the time to maintain `sc` beyond applying pull requests any more.

**Comment by slackhead** [comment] 2020-06-09 22:25
sc doesn't open csv files.  you need to convert them to sc format with psc.  E.G.:

```
cat file.csv | psc -k -d , > file.sc
``

**Comment by Arumes** [comment] 2024-04-24 09:25
Can we close this issue? As sc has no CSV support and doesn't claim to have it, this is not a bug. The way it's worded it's not a feature request, so for such a request I'd say we need a new issue if anyone's interested (I'm not).

**Comment by Arumes** [comment] 2024-05-02 08:13
@dtkerns last one. As I stated above sc failing to read CSV's is expected behaviour, not a bug. So that's another issue gone. (Last one form today, I promise 🙂)

**Closed** 2024-05-02 13:26 UTC
